name: Valgrind Memory Leak Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  valgrind_memory_leak_check:
    name: Valgrind Memory Leak Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make test

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install valgrind

      - name: Run Valgrind Leak Check
        run: make leaks

      - name: Print Valgrind Full Memory Leak Check Report
        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --trace-children=yes --error-exitcode=1 ./test.out

      - name: Cleanup
        run: make clean